"""Base model and table/PK mappings."""

from sqlmodel import SQLModel

# Map table name → primary key column name
TABLE_PK_MAP: dict[str, str] = {
    "paises": "id_pais",
    "regiones": "id_region",
    "comunas": "id_comuna",
    "campos": "id_campo",
    "cuarteles": "id_cuartel",
    "especies": "id_especie",
    "portainjertos": "id_portainjerto",
    "pmg": "id_pmg",
    "pmg_especies": "id_pmg_especie",
    "portainjerto_especies": "id_pe",
    "vivero_pmg": "id_vp",
    "origenes": "id_origen",
    "viveros": "id_vivero",
    "colores": "id_color",
    "susceptibilidades": "id_suscept",
    "variedades": "id_variedad",
    "variedad_susceptibilidades": "id_vs",
    "tipos_labor": "id_labor",
    "estados_fenologicos": "id_estado",
    "estados_planta": "id_estado",
    "temporadas": "id_temporada",
    "bodegas": "id_bodega",
    "catalogos": "id",
    "correlativos": "id",
    "centros_costo": "id",
    "marcos_plantacion": "id",
    "testblocks": "id_testblock",
    "testblock_hileras": "id_hilera",
    "inventario_vivero": "id_inventario",
    "movimientos_inventario": "id_movimiento",
    "posiciones_testblock": "id_posicion",
    "plantas": "id_planta",
    "inventario_testblock": "id_inventario_tb",
    "guias_despacho": "id_guia",
    "historial_posicion": "id_historial",
    "mediciones_laboratorio": "id_medicion",
    "clasificacion_cluster": "id_clasificacion",
    "umbrales_calidad": "id_umbral",
    "registros_fenologicos": "id_registro",
    "detalles_labor": "id_detalle",
    "ejecucion_labores": "id_ejecucion",
    "paquete_tecnologico": "id_paquete",
    "alertas": "id_alerta",
    "reglas_alerta": "id_regla",
    "bitacora_variedades": "id_entrada",
    "usuarios": "id_usuario",
    "roles": "id_rol",
    "audit_log": "id_log",
    "evidencia_labores": "id_evidencia",
    "variedades_log": "id_log",
    "defectos": "id",
    "defectos_variedades": "id",
    "asignaciones_testblock": "id_asignacion",
}
